"""

Revision ID: 494a7b3516fd
Revises: e9ed8e3f76f6
Create Date: 2026-04-27 12:19:24.640264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '494a7b3516fd'
down_revision: Union[str, Sequence[str], None] = 'e9ed8e3f76f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddedtext', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddedtext', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
