"""

Revision ID: e9ed8e3f76f6
Revises: 8d080ab0e980
Create Date: 2026-04-27 12:16:56.754774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e9ed8e3f76f6'
down_revision: Union[str, Sequence[str], None] = '8d080ab0e980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddedtext', 'question')
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('item', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('embeddedtext', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
